
import time
class menu():
    def mainNorm(self):
        print ('                            ____________')
        time.sleep(x/2)
        print ('                            \|M  A  I  N|\ ')
        time.sleep(x/2)
        print ('                             \|-=-=-=-=-=|\ ')
        time.sleep(x/2)
        print ('                              \|M  E  N  U|\ ')
        time.sleep(x/2)
        print ('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|')
        time.sleep(x)
        print ('|   AREA   |||||||| PERIMITER |||||||| SURFACE AREA  ||||||||    VOLUME   ||||||||')
        time.sleep(x)
        print ('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|')
        time.sleep(x)
        print ('|  SQUARE  | 1.01 |   SQUARE  | 2.01 |      CUBE     | 3.01 |     CUBE    | 4.01 |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('| TRIANGLE | 1.02 |  TRIANGLE | 2.02 |  RECTANGULAR  | 3.02 | RECTANGULAR | 4.02 |')
        time.sleep(x)
        print ('|          |      |           |      |     PRISM     |      |    PRISM    |      |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('|  CIRCLE  | 1.03 |   CIRCLE  | 2.03 |   TRIANGULAR  | 3.03 |  TRIANGULAR | 4.03 |')
        time.sleep(x)
        print ('|          |      |           |      |     PRISM     |      |    PRISM    |      |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('|    TBA   | 1.04 |    TBA    | 2.04 |      CONE     | 3.04 |     CONE    | 4.04 |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('|    TBA   | 1.05 |    TBA    | 2.05 |  RECTANGULAR  | 3.05 | RECTANGULAR | 4.05 |')
        time.sleep(x)
        print ('|          |      |           |      |    PYRAMID    |      |  PYRAMID    |      |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('|    TBA   | 1.06 |    TBA    | 2.06 |   TRIANGULAR  | 3.06 |  TRIANGULAR | 4.06 |')
        time.sleep(x)
        print ('|          |      |           |      |    PYRAMID    |      |   PYRAMID   |      |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('|    TBA   | 1.07 |    TBA    | 2.07 |     SPHERE    | 3.07 |    SPHERE   | 4.07 |')
        time.sleep(x)
        print ('|++++++++++|++++++|+++++++++++|++++++|+++++++++++++++|++++++|+++++++++++++|++++++|')
        time.sleep(x)
        print ('|    TBA   | 1.08 |    TBA    | 2.08 |    CYLINDER   | 3.08 |   CYLINDER  | 4.08 |')
        time.sleep(x)
        print ('|-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=|')
        time.sleep(x)
        print ('|      OTHER      ||||||||||')
        time.sleep(x)
        print ('|-=-=-=-=-=-=-=-=-=-=-=-=|||')
        time.sleep(x)
        print ('|++++++++++++++++++++++++|||')
        time.sleep(x)
        print ('|       EXIT      | 0.03 |||')
        time.sleep(x)
        print ('|++++++++++++++++++++++++|||')
        time.sleep(x)
        print ('|     SHOW MENU   | 0.04 |||')
        time.sleep(x)
        print ('|++++++++++++++++++++++++|||')
        time.sleep(x)
        return

